spring:
  cloud:
    config:
      server:
        native:
          search-locations: 
            - file:./Capstone-Project-Configurations/platform
            - file:./Capstone-Project-Configurations/services
